### ISSUE TITLE
add an events page

### ISSUE THREAD

**Issue by madhums** [DaanMeijer/extinction-rebellion-nl#8]
Right now we have an events page which points to facebook and meetup, would be nice to fetch events from fb api's and display them on the website. This would increase the user engagement and help us with mobilizing more people.

Perhaps it would be nice to have a events detail page.

**Comment by madhums** [comment]
We could use [import-facebook-events](https://wordpress.org/plugins/import-facebook-events/) plugin.

**Comment by madhums** [comment]
I am kind of afraid that this might not work anymore because facebook has disabled their graph api to fetch events and in order to get `manage_pages` permission (which you need), you need to register a business on facebook.

Wondering what options we have left!

**Comment by madhums** [comment]
I think we can simply use [import-meetup-events](https://wordpress.org/plugins/import-meetup-events/) plugin and use meetup instead of facebook

**Comment by SamLubbers** [comment]
I will try the option you suggest and share my progress here.
